### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by scottfurry** [boostorg/boostbook#16]
Selecting the link http://boost.org/libs/boostbook on the github page results in a page with the error message:

    404 Not Found
    File "/home/www/shared/archives/live/boost_1_80_0/libs/boostbook/" not found.
    Unable to find file.

Boost Org header for page appears correct. Footer shows missing Revised date (variable name showing).

**Comment by glenfe** [comment]
Fixed to be the correct link: boost.org/tools/boostbook
